[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
    "cd backend",
    "python -m venv venv",
    "source venv/bin/activate",
    "pip install -r requirements.txt"
]

[start]
cmd = "cd backend && source venv/bin/activate && gunicorn app:app"
